version: '3.7'

services:

x-common-variables: &common-variables
  NATSHOST: natsstreaming
  PORT: 3000
  JAEGER_AGENT_HOST: ${JAEGER_AGENT_HOST:-jaeger}

services:

  otf-align:
    image: nsip/otf-align
    #build: https://7f4da21a1d2a8fcea4c7376f2f85a6152dfc8531@github.com/nsip/otf-align.git#docker
    environment:
      <<: *common-variables
    ports:
      - ${TOPPORT:-40}01:3000

  otf-classifier:
    image: nsip/otf-classifier
    #build: https://7f4da21a1d2a8fcea4c7376f2f85a6152dfc8531@github.com/nsip/otf-classifier.git#docker
    environment:
      <<: *common-variables
    ports:
      - ${TOPPORT:-40}02:3000

  otf-level:
    image: nsip/otf-level
    #build: https://7f4da21a1d2a8fcea4c7376f2f85a6152dfc8531@github.com/nsip/otf-level.git#docker
    environment:
      <<: *common-variables
    ports:
      - ${TOPPORT:-40}03:3000

    # TEMP
    #n3-web:
    #image: nsip/n3-web
    ##build: https://7f4da21a1d2a8fcea4c7376f2f85a6152dfc8531@github.com/nsip/n3-web.git#docker

    #environment: *common-variables
    #environment:
    #  <<: *common-variables

  otf-reader-lpofa-literacy:
    image: nsip/otf-reader
    environment: *common-variables
    volumes:
      - ./data/otfdata/in/spa:/data
      - ./reader/config/lpofa_literacy_config.json:/config.json
    depends_on:
      - natsstreaming

  otf-reader-lpofa-literacy2:
    image: nsip/otf-reader
    environment: *common-variables
    volumes:
      - ./data/otfdata/in/spa:/data
      - ./reader/config/lpofa_literacy_config.json:/config.json
    depends_on:
      - natsstreaming

  otf-reader-lpofa-numeracy:
    image: nsip/otf-reader
    environment:
      <<: *common-variables
    volumes:
      - ./data/otfdata/in/lpofa:/data
      - ./reader/config/lpofa_numeracy_config.json:/config.json
    depends_on:
       - natsstreaming

  otf-reader-maths-pathway:
    image: nsip/otf-reader
    environment:
      <<: *common-variables
    volumes:
      - ./data/otfdata/in/maths-pathway:/data
      - ./reader/config/mp_config.json:/config.json
    depends_on:
       - natsstreaming

  otf-reader-spa-perscribed:
    image: nsip/otf-reader
    environment:
      <<: *common-variables
    volumes:
      - ./data/otfdata/in/spa:/data
      - ./reader/config/spa_prescribed_config.json:/config.json
    depends_on:
       - natsstreaming

  otf-reader-alighment-service:
    image: nsip/otf-reader
    environment:
      <<: *common-variables
    volumes:
      - ./data/otfdata/in/align:/data
      - ./reader/config/alignMaps_config.json:/config.json
    depends_on:
       - natsstreaming

  otf-reader-levelling-service:
    image: nsip/otf-reader
    environment:
      <<: *common-variables
    volumes:
      - ./data/otfdata/in/level:/data
      - ./reader/config/levelMaps.json:/config.json
    depends_on:
       - natsstreaming

  otf-reader-brightpath-data:
    image: nsip/otf-reader
    environment:
      <<: *common-variables
    volumes:
      - ./data/otfdata/in/brightpath:/data
      - ./reader/config/bp_config.json:/config.json
    depends_on:
       - natsstreaming

  otf-reader-rdr-spa-mapped:
    image: nsip/otf-reader
    environment:
      <<: *common-variables
    volumes:
      - ./data/otfdata/in/spa:/data
      - ./reader/config/spa_mapped_config.json:/config.json
    depends_on:
       - natsstreaming

  natsstreaming:
    image: nats-streaming
    ports:
      - ${TOPPORT:-40}44:4444
