http:
  address: 0.0.0.0:4195
  debug_endpoints: true

input:
  type: read_until
  read_until:
    input:
      type: file
      file:
        multipart: true
        path: /sample_data.txt
    restart_input: true
    condition:
      type: static
      static: false

pipeline:
  threads: 1
  processors:
  - type: split
    split:
      size: 5

  - type: process_dag
    process_dag:
      sometimes_404:
        premap:
          content: root.body.content
        processors:
        - type: http
          http:
            request:
              url: "http://httpbin/status/200,200,404"
            parallel: true
        - type: for_each
          for_each:
          - type: insert_part
            insert_part:
              index: 0
              content: '{"value":"hello world"}'
          - type: select_parts
        postmap:
          sometimes_404.value: value

      echo_fields:
        premap:
          body: root.body.content
        premap_optional:
          tile: root.title.content
          description: root.ingress.content
        processors:
        - type: http
          http:
            request:
              url: http://httpbin/post
            parallel: true
        postmap:
          echo.body: json.body
        postmap_optional:
          echo.title: json.title
          echo.ingress: json.description

      needs_all_fields:
        premap:
          body: root.body.content
          title: root.title.content
          description: root.ingress.content
        processors:
        - type: http
          http:
            request:
              url: http://httpbin/post
            parallel: true
        postmap:
          echo.body: json.body
          echo.title: json.title
          echo.ingress: json.description
        conditions:
          - type: jmespath
            jmespath:
              query: 'root.ingress.content != null'
          - type: jmespath
            jmespath:
              query: 'root.title.content != null'

output:
  type: drop

logger:
  prefix: service
  level: INFO

metrics:
  prometheus:
    prefix: benthos

tracer:
  jaeger:
    agent_address: 'jaeger:6831'
